version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"

  - package-ecosystem: "terraform"
    directory: "/environments/dev"
    schedule:
      interval: "monthly"
    labels:
      - "dependencies"
      - "terraform"

  - package-ecosystem: "terraform"
    directory: "/bootstrap"
    schedule:
      interval: "monthly"
    labels:
      - "dependencies"
      - "terraform"
